### ISSUE TITLE
The hallucinations are strong

### ISSUE THREAD

**Issue by robertDouglass** [AI-ANK/PaLM-Kosmos-Vision#3]
Most of the answers I get about the images are pure fiction. I uploaded a screenshot of a PDF business report and asked what it was about, and it told me it was for submitting software bugs and asking for support. 

Is the model able to read any text?

**Comment by AI-ANK** [comment]
Thank you for your feedback. The capabilities of our PaLM-Kosmos-Vision app are directly linked to the KOSMOS-2 model, which excels in general image understanding but has limited ability in text recognition within images. This is a known limitation of the KOSMOS-2 model, as detailed in its [documentation](https://arxiv.org/pdf/2306.14824.pdf). Therefore, the issue you encountered is related to the inherent capabilities of KOSMOS-2, not a specific problem with our implementation.

Closing this issue as it's beyond the scope of our current project.
